before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w -extldflags '-static' -X github.com/signmykeyio/signmykey/cmd.versionString={{.Version}}"
    targets:
      - linux_386
      - linux_amd64
      - linux_arm
      - windows_amd64
      - darwin_amd64
dist: bin
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  skip: true
nfpms:
  - maintainer: Pablo RUTH <contact@pablo-ruth.fr>
    homepage: https://github.com/signmykeyio/signmykey
    vendor: signmykey.io
    description: An automated SSH Certificate Authority
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    rpm:
      group: admin
    overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
        replacements:
          amd64: x86_64
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
